### ISSUE TITLE
NullPointerException when rendering some items from the sample item package

### ISSUE THREAD

**Issue by esotrope** [SmarterApp/TDS_IRIS#1]
<h4>Environment</h4>

- java 1.7
- tomcat 7.0.76 (http://mirrors.sonic.net/apache/tomcat/tomcat-7/v7.0.76)
- iris 1.0.3 (https://airdev.artifactoryonline.com/airdev/libs-releases-local/org/opentestsystem/delivery/iris/1.0.3)
- sample items: (ftp://ftps.smarterbalanced.org/~sbacpublic/Public/ImplementationReadiness/2015.08.19.IrpTestPackageAndContent.zip)

<h4>Steps to reproduce</h4>

1. Open sample page: http://localhost:8080/iris/IrisPages/sample.xhtml
2. Enter the following text into the topmost text area: {"passage":{"autoLoad":"false"},"items":[{"response":"RESPONSE","id":"I-187-1615"}]}
3. Click "Load Token" button

<h4>Expected</h4>

Item to render

<h4>Actual</h4>

Browser alert with stack trace
![screen shot 2017-03-28 at 10 53 33 am](https://cloud.githubusercontent.com/assets/23462925/24419687/d60ef0b6-13a4-11e7-97b2-4f4fef67f926.png)

<h4>Stack trace</h4>
Mar 28, 2017 10:02:21 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [appServlet] in context with path [/iris] threw exception [Request processing failed; nested exception is tds.itemrenderer.webcontrols.rendererservlet.ContentRenderingException: java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at tds.itemrenderer.web.ITSDocumentXmlSerializable.writeAttachments(ITSDocumentXmlSerializable.java:290)
	at tds.itemrenderer.web.ITSDocumentXmlSerializable.writeItem(ITSDocumentXmlSerializable.java:218)
	at tds.itemrenderer.web.ITSDocumentXmlSerializable.writeItems(ITSDocumentXmlSerializable.java:177)
	at tds.itemrenderer.web.ITSDocumentXmlSerializable.writeDocument(ITSDocumentXmlSerializable.java:114)
	at tds.itemrenderer.web.ITSDocumentXmlSerializable.writeXml(ITSDocumentXmlSerializable.java:75)
	at tds.student.web.handlers.BaseContentRendererController.renderGroup(BaseContentRendererController.java:71)
	at tds.iris.web.handlers.IrisWebHandler.loadContentRequest(IrisWebHandler.java:90)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:920)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:801)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at AIR.Common.Web.Session.CaseInsensitiveFileNameFilter.doFilter(CaseInsensitiveFileNameFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at AIR.Common.Web.Session.HttpContextInitializerFilter.doFilterInternal(HttpContextInitializerFilter.java:47)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at AIR.Common.Web.Session.HttpRequestLoggerInitializerFilter.doFilter(HttpRequestLoggerInitializerFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

<h4>Items found to cause the same issue</h4>

[iris-items-causing-npe.txt](https://github.com/SmarterApp/TDS_ItemRenderer/files/876560/iris-items-causing-npe.txt)

This also appears to be an issue with the IRIS application in the Smarter Balanced staging environment: https://tds-stage.smarterbalanced.org/iris/IrisPages/sample.xhtml

**Comment by alexdean201** [comment]
In this case, item 1615 is a word list glossary (WIT) item and not an assessment item.  A check of the item XML shows that it is a word list item.  Word list items do not contain the required XML elements or HTML snippets for IRIS to render.  Rather, they are to be used in conjunction with an assessment item.

Item 1576 correctly uses item 1615 to display glossary terms:

{"passage":{"autoLoad":"true"},"items": [{"response": "","id": "I-187-1576"}],"accommodations": [{"type": "Word List","codes": ["TDS_WL_KoreanGloss"]}]}

**Comment by esotrope** [comment]
Confirmed that all items causing this issue are of type "wordList" as described in their item.xml
